"""add views column to projects

Revision ID: 71587b90c764
Revises: 
Create Date: 2025-03-30 20:58:32.124815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '71587b90c764'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'user_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('profiles', 'phone_number',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'])
    op.add_column('projects', sa.Column('distribution_channel', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('objective', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('strategy_details', sa.String(length=1000), nullable=True))
    op.add_column('projects', sa.Column('references', sa.String(length=500), nullable=True))
    op.add_column('projects', sa.Column('note', sa.String(length=1000), nullable=True))
    op.add_column('projects', sa.Column('experience_points', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('quest_page_view', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('result_open_rate', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('result_click_through_rate', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('result_conversion_rate', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('result_unsubscribe_rate', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('result_imported_at', sa.Date(), nullable=True))
    op.alter_column('projects', 'status',
               existing_type=mysql.ENUM('draft', 'in_progress', 'completed', collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('projects', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'views',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.drop_constraint('projects_ibfk_1', 'projects', type_='foreignkey')
    op.alter_column('users', 'level',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'level',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.create_foreign_key('projects_ibfk_1', 'projects', 'users', ['user_id'], ['id'])
    op.alter_column('projects', 'views',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('projects', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('draft', 'in_progress', 'completed', collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    op.drop_column('projects', 'result_imported_at')
    op.drop_column('projects', 'result_unsubscribe_rate')
    op.drop_column('projects', 'result_conversion_rate')
    op.drop_column('projects', 'result_click_through_rate')
    op.drop_column('projects', 'result_open_rate')
    op.drop_column('projects', 'quest_page_view')
    op.drop_column('projects', 'experience_points')
    op.drop_column('projects', 'note')
    op.drop_column('projects', 'references')
    op.drop_column('projects', 'strategy_details')
    op.drop_column('projects', 'objective')
    op.drop_column('projects', 'distribution_channel')
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.alter_column('profiles', 'phone_number',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.alter_column('profiles', 'user_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
