name: Deploy to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: app-002-step3-2-py-oshima14
  AZURE_WEBAPP_PACKAGE_PATH: 'rebema-backend'
  PYTHON_VERSION: '3.12'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python version
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        pip install -r requirements.txt

    - name: Prepare deployment package
      run: |
        # デプロイメントディレクトリの作成
        mkdir -p ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/deployment
        
        # startup.shの権限設定
        chmod +x ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/startup.sh
        
        # 環境変数の設定
        cat > ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/.env << EOL
        WEBSITES_PORT=8000
        SCM_DO_BUILD_DURING_DEPLOYMENT=true
        PYTHON_PATH=/home/site/wwwroot
        WEBSITE_ENABLE_APP_SERVICE_STORAGE=true
        STARTUP_COMMAND=bash rebema-backend/startup.sh
        EOL
        
        # パッケージの作成
        cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        tar -czf ../output.tar.gz .
        
        # パッケージの内容確認
        echo "=== Package Contents ==="
        tar -tvf ../output.tar.gz
        
        # パッケージの場所を確認
        echo "=== Package Location ==="
        ls -la ../output.tar.gz

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./output.tar.gz
        startup-command: bash rebema-backend/startup.sh 