name: Deploy to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: app-002-step3-2-py-oshima14
  AZURE_WEBAPP_PACKAGE_PATH: 'rebema-backend'
  PYTHON_VERSION: '3.12'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python version
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        pip install -r requirements.txt

    - name: Prepare deployment package
      run: |
        # 現在のディレクトリ構造を確認
        echo "=== Current Directory Structure ==="
        ls -la
        
        # startup.shの権限設定
        chmod +x ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/startup.sh
        
        # パッケージの作成（rebema-backendディレクトリごと含める）
        tar -czf package.tar.gz ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        
        # パッケージの内容確認
        echo "=== Package Location ==="
        ls -la package.tar.gz
        
        echo "=== Package Contents ==="
        tar -tvf package.tar.gz

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: package.tar.gz 