name: Deploy to Azure Web App

on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: app-002-step3-2-py-oshima14
  AZURE_WEBAPP_PACKAGE_PATH: rebema-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          pip install -r requirements.txt

      - name: Create deployment package
        run: |
          # 現在のディレクトリ構造を確認
          echo "=== Current Directory Structure ==="
          pwd
          ls -la
          
          # wwwrootディレクトリを作成
          mkdir -p deploy_package/home/site/wwwroot
          
          # アプリケーションファイルを正しい場所にコピー
          cp -r ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} deploy_package/home/site/wwwroot/
          
          # startup.shの実行権限を設定
          chmod +x deploy_package/home/site/wwwroot/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/startup.sh
          
          # デプロイ設定ファイルを作成
          echo '{
            "name": "rebema-app",
            "startupCommand": "bash rebema-backend/startup.sh",
            "platform": {
              "os": "linux",
              "buildVersion": "Python|3.12"
            },
            "build": {
              "commands": []
            }
          }' > deploy_package/.deployment
          
          # パッケージを作成（wwwrootの親ディレクトリから）
          cd deploy_package
          zip -r ../package.zip .
          
          # パッケージの内容を確認
          echo "=== Package Contents ==="
          cd ..
          unzip -l package.zip
          
          # 重要なファイルの存在確認
          echo "=== Verifying Critical Files ==="
          unzip -l package.zip | grep -E "startup.sh|requirements.txt|main.py"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: package.zip
          clean: true 