name: Deploy to Azure Web App

on:
  push:
    branches: [ main ]

env:
  AZURE_WEBAPP_NAME: app-002-step3-2-py-oshima14
  AZURE_WEBAPP_PACKAGE_PATH: rebema-backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create deployment package
        run: |
          # パッケージの作成（rebema-backendディレクトリごと含める）
          zip -r package.zip ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          
          # startup.shの実行権限を設定
          chmod +x ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/startup.sh
          
          # パッケージの内容を確認
          echo "=== Package Contents ==="
          unzip -l package.zip
          
          # 重要なファイルの存在確認
          echo "=== Verifying Critical Files ==="
          unzip -l package.zip | grep -E "startup.sh|requirements.txt|main.py"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: package.zip
          clean: true 