name: Deploy to Azure Web App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: app-002-step3-2-py-oshima14
  AZURE_WEBAPP_PACKAGE_PATH: 'rebema-backend'
  PYTHON_VERSION: '3.12'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python version
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Create and start virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        pip install -r requirements.txt

    - name: Prepare deployment package
      run: |
        # デプロイ用の一時ディレクトリを作成
        mkdir -p deploy_package
        
        # バックエンドファイルをデプロイディレクトリにコピー
        cp -r ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/* deploy_package/
        
        # startup.shの権限設定
        chmod +x deploy_package/startup.sh
        
        # 環境変数の設定
        cat > deploy_package/.env << EOL
        WEBSITES_PORT=8000
        SCM_DO_BUILD_DURING_DEPLOYMENT=true
        PYTHON_PATH=/home/site/wwwroot
        WEBSITE_ENABLE_APP_SERVICE_STORAGE=true
        EOL
        
        # パッケージの作成
        cd deploy_package
        zip -r ../package.zip .
        cd ..
        
        # パッケージの確認
        echo "=== Package Location ==="
        ls -la package.zip
        
        echo "=== Package Contents ==="
        unzip -l package.zip

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: package.zip 